<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin-PC" name="RetryMultipleFailedTestCases" tests="7" failures="2" timestamp="21 Aug 2019 17:15:44 GMT" time="0.082" errors="0">
  <testcase name="Test1" time="0.018" classname="MyTests.RunTimeTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="MyTests.RunTimeTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="MyTests.RunTimeTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at MyTests.RunTimeTests.Test1(RunTimeTests.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.003" classname="MyTests.RunTimeTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="MyTests.RunTimeTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="MyTests.RunTimeTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at MyTests.RunTimeTests.Test2(RunTimeTests.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="MyTests.RunTimeTests"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
